### ISSUE TITLE
Crash on loading

### ISSUE THREAD

**Issue by massimocolaceci** [tabulartools/pbi-explorer#78]
### Describe the problem

Hi, 
On loading PbiExplorer.exe as a stand-alone app (instead of from PBI Desktop), and selecting a PBIX to open, a pop-up informs a .NET error (see screenshot).
By clicking on "Continue", I'm able to navigate through the app page and use some features, but then it crashes again.
The issue is occurring with a report whose 1st page has very high number of visuals (261), I wonder if it might causing the issue.
I'm not experimenting the issue with other, much smaller reports.

Thanks

### PBI Explorer

0.7.1

### Power BI

2.124.1052.0 64-bits  (Dec 2023)

### Windows

Windows 11 Home Single Language, 23H2

### Steps to reproduce the behavior

1. Run PbiExplorer.exe
2. Click on the "Inspect report" button
3. select the PBIX file, then "Open"
4. the error message pops-up

### Additional context

Consulte o final desta mensagem para obter detalhes sobre como chamar a 
depuração just-in-time (JIT) em vez desta caixa de diálogo.

************** Texto de Exceção **************
System.ArgumentException: Value does not fall within the expected range.
   at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2.NavigateToString(String htmlContent)
   at Microsoft.Web.WebView2.Core.CoreWebView2.NavigateToString(String htmlContent)
   at PbiExplorer.UI.Components.PbiExplorerWebView.NavigateToStringCoreAsync(String htmlContent, Boolean zoomToFit)
   at PbiExplorer.UI.Components.PbiExplorerWebView.NavigateToStringAsync(String htmlContent, Boolean zoomToFit)
   at PbiExplorer.UI.Views.ReportInspectorView.SetWebUiPageAsync(Page page)
   at PbiExplorer.UI.Views.ReportInspectorView.AppOnInspectorFileLoaded(Object sender, EventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)

************** Assemblies Carregados **************
System.Private.CoreLib
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
PbiExplorer
    Versão do Assembly: 0.7.1.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.Runtime
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
Microsoft.Extensions.DependencyInjection.Abstractions
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
DevExpress.Utils.v23.1
    Versão do Assembly: 23.1.6.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.Windows.Forms
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.ComponentModel.Primitives
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.Windows.Forms.Primitives
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.Runtime.InteropServices
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.Drawing.Primitives
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.Collections.Specialized
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.Drawing.Common
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
DevExpress.Data.v23.1
    Versão do Assembly: 23.1.6.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
netstandard
    Versão do Assembly: 2.1.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.Threading
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.Diagnostics.TraceSource
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
Microsoft.ApplicationInsights
    Versão do Assembly: 2.21.0.429
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
Microsoft.Extensions.Hosting
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
Microsoft.Extensions.Hosting.Abstractions
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
Microsoft.Extensions.Configuration.Abstractions
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.ComponentModel
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
Serilog
    Versão do Assembly: 2.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
Microsoft.Extensions.DependencyInjection
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
Serilog.Extensions.Hosting
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.Diagnostics.DiagnosticSource
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.Diagnostics.Tracing
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.IO.MemoryMappedFiles
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.Private.Uri
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.Collections.Concurrent
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
Microsoft.Extensions.FileProviders.Abstractions
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
Microsoft.Extensions.FileProviders.Physical
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
Microsoft.Extensions.Primitives
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
Microsoft.Extensions.Configuration
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
Microsoft.Extensions.Configuration.EnvironmentVariables
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
Microsoft.Extensions.Configuration.FileExtensions
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
Microsoft.Extensions.Configuration.Binder
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
Microsoft.Extensions.Configuration.Json
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.Linq
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.Collections
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.IO.FileSystem.Watcher
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.Threading.Overlapped
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
Microsoft.Extensions.Options
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
Microsoft.Extensions.Logging
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
Microsoft.Extensions.Logging.Abstractions
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
Microsoft.Extensions.Logging.EventLog
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
Microsoft.Extensions.Logging.Configuration
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
Microsoft.Extensions.Options.ConfigurationExtensions
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
Microsoft.Extensions.Logging.Console
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.Text.Json
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
Microsoft.Extensions.Logging.Debug
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
Microsoft.Extensions.Logging.EventSource
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
Serilog.Extensions.Logging
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
Serilog.Sinks.ApplicationInsights
    Versão do Assembly: 4.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
Serilog.Enrichers.Sensitive
    Versão do Assembly: 1.7.3.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.Text.RegularExpressions
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.Reflection.Emit.ILGeneration
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.Reflection.Primitives
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.Private.Xml.Linq
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.Private.Xml
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
PbiExplorer.BestPracticeAnalyzer
    Versão do Assembly: 0.7.1.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.ObjectModel
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
Newtonsoft.Json
    Versão do Assembly: 13.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.Runtime.Serialization.Formatters
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.Linq.Expressions
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.Runtime.Numerics
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.Runtime.Serialization.Primitives
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.Data.Common
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.Xml.ReaderWriter
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.ComponentModel.TypeConverter
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
PbiTools.ReportModel
    Versão do Assembly: 0.7.1.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.Memory
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Versão do Assembly: 0.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.Resources.Extensions
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
mscorlib
    Versão do Assembly: 4.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.Collections.NonGeneric
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
DevExpress.Drawing.v23.1
    Versão do Assembly: 23.1.6.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.Threading.Thread
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.Configuration.ConfigurationManager
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.Diagnostics.Process
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.Security.Cryptography
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.Net.WebClient
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.ComponentModel.EventBasedAsync
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System
    Versão do Assembly: 4.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
DevExpress.Data.Desktop.v23.1
    Versão do Assembly: 23.1.6.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
Microsoft.Win32.SystemEvents
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.IO.Compression
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
Microsoft.Win32.Registry
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
PbiExplorer.Shared
    Versão do Assembly: 0.7.1.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
Accessibility
    Versão do Assembly: 4.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
DevExpress.XtraLayout.v23.1
    Versão do Assembly: 23.1.6.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
DevExpress.XtraEditors.v23.1
    Versão do Assembly: 23.1.6.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
DevExpress.Printing.v23.1.Core
    Versão do Assembly: 23.1.6.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
DevExpress.XtraTreeList.v23.1
    Versão do Assembly: 23.1.6.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
Microsoft.Web.WebView2.WinForms
    Versão do Assembly: 1.0.2088.41
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
Microsoft.Web.WebView2.Core
    Versão do Assembly: 1.0.2088.41
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
DevExpress.XtraVerticalGrid.v23.1
    Versão do Assembly: 23.1.6.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.Diagnostics.StackTrace
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.Numerics.Vectors
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.ComponentModel.Annotations
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
DevExpress.XtraBars.v23.1
    Versão do Assembly: 23.1.6.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.Runtime.Loader
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.Windows.Forms.resources
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.Net.Http
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.Net.Primitives
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.Net.Security
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.Net.Quic
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.Net.Sockets
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
Microsoft.Win32.Primitives
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.Net.NameResolution
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.Threading.ThreadPool
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.Security.Principal.Windows
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.Security.Claims
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
Newtonsoft.Json.Schema
    Versão do Assembly: 3.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.Windows.Extensions
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.IO.Packaging
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.Reflection.Metadata
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.Collections.Immutable
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.Net.NetworkInformation
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.Linq.Queryable
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.Linq.Dynamic.Core
    Versão do Assembly: 1.3.5.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.IO.FileSystem.DriveInfo
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.Resources.Writer
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.Xml.XmlSerializer
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.Diagnostics.EventLog
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.Console
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.Reflection.Emit.Lightweight
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.Xml.XDocument
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.Formats.Asn1
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.Net.Requests
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
WindowsBase
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.Security.AccessControl
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
DevExpress.Sparkline.v23.1.Core
    Versão do Assembly: 23.1.6.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.ServiceModel.Primitives
    Versão do Assembly: 4.10.2.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.Private.ServiceModel
    Versão do Assembly: 4.10.2.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
DevExpress.Pdf.v23.1.Core
    Versão do Assembly: 23.1.6.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.Threading.Tasks
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.Drawing
    Versão do Assembly: 7.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------

************** Depuração JIT **************

### Screenshots

![image](https://github.com/tabulartools/pbi-explorer/assets/49816615/f93bd04f-153c-4770-94ed-5436e5213691)

**Comment by DBojsen** [comment]
Hi @massimocolaceci 

Can you open other reports without issues?

Would it be possible for you to share the report in pbit format (without data) and/or a video of the issue with us at support@tabulartools.com ?

BR David - Tabular Tools

**Comment by massimocolaceci** [comment]
Hi,

Thanks for your prompt reply. I apologize to get you back so late.
Unluckily, I'm not able to reproduce the issue, because the PBIX file is no
longer available.

However, I appreciate your attention so far.

Thank you

Regards

Massimo Colaceci

Em ter., 16 de jan. de 2024 às 07:59, David Bojsen ***@***.***>
escreveu:
